name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          OWNER="${GITHUB_REPOSITORY_OWNER,,}"
          IMAGE="ghcr.io/$OWNER/aws-experiment:latest"
          docker build -t "$IMAGE" .

      - name: Push Docker image
        run: |
          OWNER="${GITHUB_REPOSITORY_OWNER,,}"
          IMAGE="ghcr.io/$OWNER/aws-experiment:latest"
          docker push "$IMAGE"


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

          
      - name: Test AWS via Lambda
        run: |
          echo "Invoking Lambda HelloStudentFunction from CI..."

          aws lambda invoke \
            --function-name HelloStudentFunction \
            --payload '{"name": "Anton from CI"}' \
            --cli-binary-format raw-in-base64-out \
            lambda_response.json

          echo "Raw Lambda response file:"
          cat lambda_response.json
      
      - name: Copy deploy files (docker-compose.yml)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/app/"
          overwrite: true
          debug: true      

      - name: Deploy container on EC2 over SSH
        uses: appleboy/ssh-action@v0.1.10
        env:
            GHCR_PAT: ${{ secrets.GHCR_PAT }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GHCR_PAT 
          script: |
            set -xe

            cd /home/ubuntu/app

            echo "$GHCR_PAT" | sudo docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

            docker compose pull
            docker compose up -d

            echo "Deploy via docker-compose finished OK"